_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 49
                - 55
                - 71
            "2":
                - 1
                - 49
                - 55
                - 71
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
batch_size:
    value: 32
block_overlap:
    value: 8
block_widths:
    value:
        - 8
        - 16
        - 32
        - 64
channel_kl_loss_weight:
    value: 0.1
channel_mult:
    value:
        - 1
        - 2
        - 4
data_dir:
    value: dataset/processed
eval_every:
    value: 100
latent_channels:
    value: 32
learning_rate:
    value: 0.0001
max_steps:
    value: 100000
model_channels:
    value: 64
num_layers_per_block:
    value: 2
num_workers:
    value: 4
output_dir:
    value: outputs/vae
pad_to_length:
    value: 256
recon_loss_weight:
    value: 0.1
save_every:
    value: 1000
